feat: implement Bookmark
f-lab-clone/ticketing-service pull request #28
Opened 2023-07-12 10:24 UTC by ParkJeongseop

#  What is this PR?
- Github Issue: #23 

**작업 진행중**
 
# Key Changes
- 북마크 기본 구조 구성

# Test Checklist
controller
- [ ] BookmarkContoller.create(...)는 bookmarkService.create()를 호출해야 한다.
- [ ] BookmarkContoller.create(...)가 정상적으로 호출되면 200 success를 반환한다.
- [ ] BookmarkContoller.create(...)에 빈값을 넣으면 400 error를 반환한다.

service
- [ ] bookmarkService.create(...)는 repository.save()을 호출한다.

repository

2023-07-15 10:35 UTC, junha-ahn requested changes
매우매우 매우 좋습니다 쵝오

2023-07-15 10:35 UTC, junha-ahn commented on src/test/kotlin/com/group4/ticketingservice/TicketingserviceApplicationTests.kt
> +        return true
https://javaju.tistory.com/128

해당 test 에러 관련된 글들이 있네요. 보고 확인해서 수정 부탁드립니다!

2023-07-15 10:35 UTC, junha-ahn commented
차후 git issue화
- json type request 지원 (및 테스트 변경)

2023-07-15 10:41 UTC, junha-ahn commented
추가 테스트 시나리오
- bookmarkService.getList()가 [] (빈 리스트)을 반환하는지 확인

db mockup으로 가능하다면
- bookmarkService.create(...)를 호출한 후, 데이터베이스에 해당 북마크가 제대로 저장되었는지 확인. - 북마크를 다시 조회 - bookmarkService.delete(id)를 호출한 후, 데이터베이스에서 해당 북마크가 제거되었는지 확인합니다. - 북마크를 다시 조회

2023-07-15 10:53 UTC, junha-ahn commented on src/test/kotlin/com/group4/ticketingservice/bookmark/BookmarkControllerTest.kt
> +    fun `GET_api_bookmark should return HTTP ERROR 404 if element is not found`() {
getOne에 대해 return null을 할지 404 에러를 반환할지 자료등을 찾아서 생각 정리해주시면 좋을것 같습니다.

2023-07-15 10:53 UTC, junha-ahn commented
## 추가 테스트 시나리오
- bookmarkService.getList()가 [] (빈 리스트)을 반환하는지 확인

db mockup으로 가능하다면
- bookmarkService.create(...)를 호출한 후, 데이터베이스에 해당 북마크가 제대로 저장되었는지 확인. - 북마크를 다시 조회 
- bookmarkService.delete(id)를 호출한 후, 데이터베이스에서 해당 북마크가 제거되었는지 확인합니다. - 북마크를 다시 조회

## 차후 Git issue화 또는 추가 기능
JSON request 지원

2023-07-15 11:57 UTC, bohblue2 commented
잘하셨습니다.

2023-07-16 10:34 UTC, junha-ahn requested changes

2023-07-16 10:34 UTC, junha-ahn commented on src/test/kotlin/com/group4/ticketingservice/bookmark/BookmarkServiceTest.kt
> +        verify(exactly = 1) { repository.findAll() }
음 해당 내용은 findAll을 호출하는지 테스트하는것이지, 빈리스트를 반환하는지 테스트가 아닌것 같습니다.

1. repository.findAll() => []을 반환
2. service.getList() 의 응답이 []인지 확인

2023-07-16 13:51 UTC, ParkJeongseop commented on src/test/kotlin/com/group4/ticketingservice/bookmark/BookmarkControllerTest.kt
> +    fun `GET_api_bookmark should return HTTP ERROR 404 if element is not found`() {
관련 내용을 조사해보았는데 HTTP 404 코드는 데이터를 못찾을때가 아닌 엔드포인트 자체를 못찾았을때를 의미하는 것 같습니다. 생각해보면 이렇게 구현하게되었을때  404 코드를 보고 없는 엔드포인트인지 데이터가 없는것인지 구분하지 못할듯합니다. 다른분들의 생각은 어떠십니까?

2023-07-16 14:05 UTC, junha-ahn commented on src/test/kotlin/com/group4/ticketingservice/bookmark/BookmarkControllerTest.kt
> +    fun `GET_api_bookmark should return HTTP ERROR 404 if element is not found`() {
참고 레퍼런스
- https://softwareengineering.stackexchange.com/questions/400430/use-404-or-200-when-null-result-rest
- https://apihandyman.io/empty-lists-http-status-code-200-vs-204-vs-404/

저는 개인적으로 200 null을 선호하지만 프론트 엔드 개발자 요청에 의해 404로 구현했던 기억도 있네요

2023-07-16 14:41 UTC, junha-ahn commented
위 댓글에서 남긴 db mock up 테스트는 `@DataJpaTest` 어노테이션으로 불가능합니까?
- https://twpower.github.io/293-test-jpa-repository-using-data-jpa-test

2023-07-16 16:31 UTC, junha-ahn commented on src/test/kotlin/com/group4/ticketingservice/bookmark/BookmarkControllerTest.kt
> +    fun `GET_api_bookmark should return HTTP ERROR 404 if element is not found`() {
@bohblue2 @minjun3021 @yunsuu 다들 한번 구경해보세요~

2023-07-17 05:24 UTC, hihahayoung requested changes
고생 많으셨습니다 ㅎㅎ 역쉬 에이스 JSP!!

2023-07-17 05:24 UTC, hihahayoung commented on src/main/kotlin/com/group4/ticketingservice/controller/BookmarkController.kt
> +    }
변수 이름을 동사보다는 명사나 형용사로 쓰는 편이 나을 것 같습니다.
그리고 HttpStatus를 import해서 사용하는 게 나중에 코드를 읽을 때 조금 더 직관적이지 않을까 싶네요!

`val posted = bookmarkService.create(boardFormDto)`
`return ResponseEntity.body(posted).status(HttpStatus.OK)`

2023-07-17 05:24 UTC, hihahayoung commented on src/main/kotlin/com/group4/ticketingservice/service/BookmarkService.kt
> +    }
여기서 혹시 id만 돌려주는 이유가 있을까요? 그냥 객체 자체를 돌려줘서 user_id와 show_id도 client딴에 보여주면 어떨까 하는 생각이 드네요!

2023-07-17 05:24 UTC, hihahayoung commented on src/main/kotlin/com/group4/ticketingservice/controller/BookmarkController.kt
> +        }
여기도 마찬가지로 HttpStatus를 사용하시면 좋을 듯 합니다! 밑에도 쭉~~

2023-07-17 08:44 UTC, junha-ahn commented on src/main/kotlin/com/group4/ticketingservice/service/BookmarkService.kt
> +    }
개인적으로는 해당 save후 id를 돌려줄수 있는 매커니즘이 궁금합니다. 

insert 후 select를 하는겁니까? @ParkJeongseop

2023-07-17 09:58 UTC, junha-ahn commented on src/test/kotlin/com/group4/ticketingservice/bookmark/BookmarkControllerTest.kt
> +    fun `GET_api_bookmark should return HTTP ERROR 404 if element is not found`() {
@hihahayoung no additional content 때문인지 put delete때 사용한다는 의견도 있는거 같네요 (수정,삭제에대한 추가적인 응답)

2023-07-17 13:15 UTC, junha-ahn commented on src/test/kotlin/com/group4/ticketingservice/bookmark/BookmarkControllerTest.kt
> +    fun `GET_api_bookmark should return HTTP ERROR 404 if element is not found`() {
[상태 코드, 뭘 줘야할까?](https://tecoble.techcourse.co.kr/post/2020-08-31-http-status-code/) 이 글이 정말 좋네요.

@ParkJeongseop 원하시는거 하나를 선택하시면 좋을 것 같습니다!

2023-07-17 14:43 UTC, ParkJeongseop commented on src/test/kotlin/com/group4/ticketingservice/bookmark/BookmarkControllerTest.kt
> +    fun `GET_api_bookmark should return HTTP ERROR 404 if element is not found`() {
저는 200이라고 생각되는게
404는 REST API에서 엔드포인트가 없음을 의미하고
204는 response payload body에 내용이 없다라고 생각됩니다.
저희는 가져온 데이터가 null이라는 것을 표현하는것이고, 아래와 같이 데이터 반환 형식을 지정한다고 가정하였을때 null이더라도 payload body는 존재합니다. 공식문서의 204설명을 보면 PUT DELETE를 예시로 들었는데 이경우에는 성공을 하였다면 모두 204를 반환합니다. 데이터관점이 아닌 엔드포인트 관점에서 null과 null이 아닌데이터 둘다 백엔드에서 성공적으로 수행해서 나온 결과입니다. 따라서 데이터에 따라 HTTP 코드를 구분할 필요가 없다고 생각됩니다.
```json
{
    "status": "success",
    "data": 1
}
```
다른분들은 어떻게 생각하시나요?

2023-07-19 09:29 UTC, junha-ahn requested changes
좋습니다. 계속 좋아지고 있네요! (사실 코딩하시는 기간동안 읽은걸 체크하는거에 가깝네요)

2023-07-19 09:29 UTC, junha-ahn commented on src/test/kotlin/com/group4/ticketingservice/bookmark/BookmarkControllerTest.kt
> +    fun `GET_api_bookmark should return HTTP ERROR 404 if element is not found`() {
해당 부분 아직 미수정 상태입니다

2023-07-19 09:48 UTC, ParkJeongseop commented on src/main/kotlin/com/group4/ticketingservice/controller/BookmarkController.kt
> +        headers.set("Content-Location", "/bookmark/%d".format(savedBookmarkId))
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Location#pointing_to_a_new_document_http_201_created 공식문서에 생성된 객체의 위치를 반환하는 방법으로 사용되어 추가해보았습니다.

2023-07-19 13:38 UTC, junha-ahn commented on src/main/kotlin/com/group4/ticketingservice/controller/BookmarkController.kt
> +        headers.set("Content-Location", "/bookmark/%d".format(savedBookmarkId))
좋습니다. https://sanghaklee.tistory.com/57 에 있는 내용들을 학습하셔서 #36 에 정리 부탁드립니다.

2023-07-19 14:22 UTC, ParkJeongseop commented on src/main/kotlin/com/group4/ticketingservice/controller/BookmarkController.kt
> +@RequestMapping("bookmark")
/bookmark -> /bookmarks로 변경하였습니다.

2023-07-19 14:33 UTC, junha-ahn requested changes
아주 좋습니다! 다음 수정이 마지막일것 같은 예감!

2023-07-19 14:33 UTC, junha-ahn commented on src/main/kotlin/com/group4/ticketingservice/controller/BookmarkController.kt
> +    fun deleteBookmark(@PathVariable id: Long): ResponseEntity<Any> {
@bohblue2 @minjun3021  @yunsuu  참고

2023-07-19 14:50 UTC, junha-ahn commented on src/main/kotlin/com/group4/ticketingservice/controller/BookmarkController.kt
> +        headers.set("Content-Location", "/bookmark/%d".format(savedBookmarkId))
참고) 모든 Post Put API마다 해당 라인을 삽입할 수는 없으니 향후 다른 방법을 고려해야할것 같네요. (해당 PR에서는 수정할 필요 없습니다!)

2023-07-20 11:45 UTC, bohblue2 approved these changes
Gj!!

2023-07-20 11:52 UTC, junha-ahn approved these changes
GJ

2023-07-20 12:02 UTC, hihahayoung approved these changes
수고수고하셨습니다!!

2023-07-20 12:04 UTC, merged